### PR TITLE
Try to update exiv2

### PR DESCRIPTION
**Pull request by lock042**

### CODE REVIEW

**Comment by hfiguiere** [comment]
Exiv2 need some patch to build on aarch64

See https://github.com/flathub/com.rawtherapee.RawTherapee/blob/master/exiv2-build-arm.patch

**Comment by lock042** [comment]
> Exiv2 need some patch to build on aarch64
> 
> See https://github.com/flathub/com.rawtherapee.RawTherapee/blob/master/exiv2-build-arm.patch

Oh yes thank you. I've opened an issue in the exiv2 github. Apparently this is fixed in the dev branch.

**Comment by hfiguiere** [comment]
> > Exiv2 need some patch to build on aarch64
> > See https://github.com/flathub/com.rawtherapee.RawTherapee/blob/master/exiv2-build-arm.patch
> 
> Oh yes thank you. I've opened an issue in the exiv2 github. Apparently this is fixed in the dev branch.

I had already filed it a while ago. https://github.com/Exiv2/exiv2/pull/1238

**Comment by hfiguiere** [comment]
There is no need to touch the patch. Just take is as is from https://github.com/flathub/com.rawtherapee.RawTherapee/blob/master/exiv2-build-arm.patch including with the bad line endings.

(works fine here, just tested)

**Comment by hfiguiere** [comment]
If you want I can update the branch.

**Comment by lock042** [comment]
> If you want I can update the branch.

Oh yes, please

**Comment by lock042** [comment]
Thank you :)

**Pull request merged**
