### PR TITLE
restore opencv version

### PR DESCRIPTION
**Pull request by lock042**
I should write a PR . Sorry about the build issue.

### CODE REVIEW

**Comment by hfiguiere** [comment]
What is the reason of this?

**Comment by lock042** [comment]
Looks like I broke the build with opencv: https://flathub.org/builds/#/builders/48/builds/2825

**Comment by hfiguiere** [comment]
I didn't realise you had pushed changes.

**Comment by lock042** [comment]
Yes so stupid to push directly in master.

**Comment by hfiguiere** [comment]
I usually use pull request to have the build happen. At worse, I just make sure it builds locally. But even then sometime it is not enough.

**Comment by lock042** [comment]
Yes, I should have used PR.
I have to admit I don't understand why opencv4 is not taken into account, but I don't remember for Siril 0.9.12 version. Maybe it is normal.

**Comment by hfiguiere** [comment]
likely because 4 is incompatible with 3.

**Comment by lock042** [comment]
No I think they remove the pkgconfig file. They already did it in debian beore they've restored it.

**Comment by lock042** [comment]
Something like that: https://github.com/opencv/opencv/issues/13154

**Pull request merged**
