### PR TITLE
Siril: Update version to 1.2.0-rc1

### PR DESCRIPTION
**Pull request by lock042**
Update Siril version

### CODE REVIEW

**Comment by lock042** [comment]
@hfiguiere : Any idea why it fails? Why suddenly there is a problem with the icon. I have svg one. Png is now mandatory?

**Comment by hfiguiere** [comment]
> @hfiguiere : Any idea why it fails? Why suddenly there is a problem with the icon. I have svg one. Png is now mandatory?

Paging @barthalion . It's the appstream migration.

**Comment by hfiguiere** [comment]
Ah yeah:

`  <id>org.free_astro.siril.desktop</id>` in the appstream file. This is wrong but was still accepted.

see also https://github.com/ximion/appstream/issues/500

**Comment by lock042** [comment]
Not sure to understand... Need to remove: <id>org.free_astro.siril.desktop</id> ?

**Comment by barthalion** [comment]
You need to remove the `.desktop` part from `<id>`.

**Comment by lock042** [comment]
Need I write <id>org.free_astro.siril.desktop</id>?

**Comment by hfiguiere** [comment]
In the appstream file it should be `<id>org.free_astro.siril</id>` since that's the app-id.

Here: https://gitlab.com/free-astro/siril/-/blob/master/platform-specific/linux/org.free_astro.siril.appdata.xml#L4

**Pull request merged**
