### PR TITLE
New upstream version

### PR DESCRIPTION
**Pull request by lock042**
New upstream version: 1.0.6

### CODE REVIEW

**Comment by lock042** [comment]
@hfiguiere : Any idea why I have these new errors?

**Comment by hfiguiere** [comment]
We added a linter. I have pushed a change that will allow to pass.

**Comment by hfiguiere** [comment]
> We added a linter. I have pushed a change that will allow to pass.

And pushed another change because the problem was there twice.

**Comment by lock042** [comment]
Thanks a lot @hfiguiere

**Pull request merged**
