### PR TITLE
Fix JSON formatting

### PR DESCRIPTION
**Pull request by lionirdeadman**
This was broke with https://github.com/flathub/org.free_astro.siril/pull/23

### CODE REVIEW

**Comment by hfiguiere** [comment]
good call. I didn't check the other PR when I saw it.

**Comment by lock042** [comment]
Oh so sorry !!! thx!

**Comment by lionirdeadman** [comment]
Did you forget to merge it, @lock042? :sweat_smile:

**Comment by lock042** [comment]
Done ;).

Thanks a lot again.

**Pull request merged**
